package org.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAPPROLE<M extends BaseAPPROLE<M>> extends Model<M> implements IBean {

	public void setROLEID(java.math.BigDecimal ROLEID) {
		set("ROLEID", ROLEID);
	}

	public java.math.BigDecimal getROLEID() {
		return get("ROLEID");
	}

	public void setROLENAME(java.lang.String ROLENAME) {
		set("ROLENAME", ROLENAME);
	}

	public java.lang.String getROLENAME() {
		return get("ROLENAME");
	}

	public void setDELFLAG(java.lang.Integer DELFLAG) {
		set("DELFLAG", DELFLAG);
	}

	public java.lang.Integer getDELFLAG() {
		return get("DELFLAG");
	}

}
