package org.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApproleMenu<M extends BaseApproleMenu<M>> extends Model<M> implements IBean {

	public void setROLEID(java.math.BigDecimal ROLEID) {
		set("ROLEID", ROLEID);
	}

	public java.math.BigDecimal getROLEID() {
		return get("ROLEID");
	}

	public void setMENUID(java.math.BigDecimal MENUID) {
		set("MENUID", MENUID);
	}

	public java.math.BigDecimal getMENUID() {
		return get("MENUID");
	}

}
