package org.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppuserRole<M extends BaseAppuserRole<M>> extends Model<M> implements IBean {

	public void setUSERID(java.lang.String USERID) {
		set("USERID", USERID);
	}

	public java.lang.String getUSERID() {
		return get("USERID");
	}

	public void setROLEID(java.math.BigDecimal ROLEID) {
		set("ROLEID", ROLEID);
	}

	public java.math.BigDecimal getROLEID() {
		return get("ROLEID");
	}

}
