package org.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAPPUSER<M extends BaseAPPUSER<M>> extends Model<M> implements IBean {

	public void setUSERID(java.lang.String USERID) {
		set("USERID", USERID);
	}

	public java.lang.String getUSERID() {
		return get("USERID");
	}

	public void setLOGINNAME(java.lang.String LOGINNAME) {
		set("LOGINNAME", LOGINNAME);
	}

	public java.lang.String getLOGINNAME() {
		return get("LOGINNAME");
	}

	public void setREALNAME(java.lang.String REALNAME) {
		set("REALNAME", REALNAME);
	}

	public java.lang.String getREALNAME() {
		return get("REALNAME");
	}

	public void setPASSWORD(java.lang.String PASSWORD) {
		set("PASSWORD", PASSWORD);
	}

	public java.lang.String getPASSWORD() {
		return get("PASSWORD");
	}

	public void setUSERSTATUS(java.lang.Integer USERSTATUS) {
		set("USERSTATUS", USERSTATUS);
	}

	public java.lang.Integer getUSERSTATUS() {
		return get("USERSTATUS");
	}

	public void setUSERTYPEID(java.lang.Integer USERTYPEID) {
		set("USERTYPEID", USERTYPEID);
	}

	public java.lang.Integer getUSERTYPEID() {
		return get("USERTYPEID");
	}

	public void setMAPID(java.lang.String MAPID) {
		set("MAPID", MAPID);
	}

	public java.lang.String getMAPID() {
		return get("MAPID");
	}

	public void setDELFLAG(java.lang.Integer DELFLAG) {
		set("DELFLAG", DELFLAG);
	}

	public java.lang.Integer getDELFLAG() {
		return get("DELFLAG");
	}

}
