package org.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerinfo<M extends BaseCustomerinfo<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public void setCustomName(java.lang.String customName) {
		set("customName", customName);
	}

	public java.lang.String getCustomName() {
		return get("customName");
	}

	public void setCard(java.lang.String card) {
		set("card", card);
	}

	public java.lang.String getCard() {
		return get("card");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setWebcart(java.lang.String webcart) {
		set("webcart", webcart);
	}

	public java.lang.String getWebcart() {
		return get("webcart");
	}

	public void setBorrowbalan(java.lang.Double borrowbalan) {
		set("borrowbalan", borrowbalan);
	}

	public java.lang.Double getBorrowbalan() {
		return get("borrowbalan");
	}

	public void setBorrowdate(java.lang.String borrowdate) {
		set("borrowdate", borrowdate);
	}

	public java.lang.String getBorrowdate() {
		return get("borrowdate");
	}

	public void setReplymoney(java.lang.Double replymoney) {
		set("replymoney", replymoney);
	}

	public java.lang.Double getReplymoney() {
		return get("replymoney");
	}

	public void setReplydate(java.lang.String replydate) {
		set("replydate", replydate);
	}

	public java.lang.String getReplydate() {
		return get("replydate");
	}

	public void setDeposit(java.lang.Double deposit) {
		set("deposit", deposit);
	}

	public java.lang.Double getDeposit() {
		return get("deposit");
	}

	public void setPlatform(java.lang.String platform) {
		set("platform", platform);
	}

	public java.lang.String getPlatform() {
		return get("platform");
	}

	public void setAgency(java.lang.String agency) {
		set("agency", agency);
	}

	public java.lang.String getAgency() {
		return get("agency");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setProfit(java.lang.Double profit) {
		set("profit", profit);
	}

	public java.lang.Double getProfit() {
		return get("profit");
	}

	public void setActualdate(java.lang.String actualdate) {
		set("actualdate", actualdate);
	}

	public java.lang.String getActualdate() {
		return get("actualdate");
	}

	public void setAcualmoney(java.lang.Double acualmoney) {
		set("acualmoney", acualmoney);
	}

	public java.lang.Double getAcualmoney() {
		return get("acualmoney");
	}

	public void setAssessorId(java.lang.String assessorId) {
		set("assessorId", assessorId);
	}

	public java.lang.String getAssessorId() {
		return get("assessorId");
	}

	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}

	public java.lang.String getFlag() {
		return get("flag");
	}

	public void setPayId(java.lang.String payId) {
		set("payId", payId);
	}

	public java.lang.String getPayId() {
		return get("payId");
	}

	public void setRevfee(java.lang.Double revfee) {
		set("revfee", revfee);
	}

	public java.lang.Double getRevfee() {
		return get("revfee");
	}

	public void setOverflag(java.lang.String overflag) {
		set("overflag", overflag);
	}

	public java.lang.String getOverflag() {
		return get("overflag");
	}

}
