package org.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAPPUSERTYPE<M extends BaseAPPUSERTYPE<M>> extends Model<M> implements IBean {

	public void setUSERTYPEID(java.lang.Integer USERTYPEID) {
		set("USERTYPEID", USERTYPEID);
	}

	public java.lang.Integer getUSERTYPEID() {
		return get("USERTYPEID");
	}

	public void setUSERTYPENAME(java.lang.String USERTYPENAME) {
		set("USERTYPENAME", USERTYPENAME);
	}

	public java.lang.String getUSERTYPENAME() {
		return get("USERTYPENAME");
	}

	public void setMAPTABLE(java.lang.String MAPTABLE) {
		set("MAPTABLE", MAPTABLE);
	}

	public java.lang.String getMAPTABLE() {
		return get("MAPTABLE");
	}

	public void setMAPFIELD(java.lang.String MAPFIELD) {
		set("MAPFIELD", MAPFIELD);
	}

	public java.lang.String getMAPFIELD() {
		return get("MAPFIELD");
	}

}
