package org.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAPPMENU<M extends BaseAPPMENU<M>> extends Model<M> implements IBean {

	public void setMENUID(java.math.BigDecimal MENUID) {
		set("MENUID", MENUID);
	}

	public java.math.BigDecimal getMENUID() {
		return get("MENUID");
	}

	public void setMENUNAME(java.lang.String MENUNAME) {
		set("MENUNAME", MENUNAME);
	}

	public java.lang.String getMENUNAME() {
		return get("MENUNAME");
	}

	public void setPARENTID(java.math.BigDecimal PARENTID) {
		set("PARENTID", PARENTID);
	}

	public java.math.BigDecimal getPARENTID() {
		return get("PARENTID");
	}

	public void setMENUURL(java.lang.String MENUURL) {
		set("MENUURL", MENUURL);
	}

	public java.lang.String getMENUURL() {
		return get("MENUURL");
	}

	public void setMENUICON(java.lang.String MENUICON) {
		set("MENUICON", MENUICON);
	}

	public java.lang.String getMENUICON() {
		return get("MENUICON");
	}

	public void setMENUSORT(java.lang.Double MENUSORT) {
		set("MENUSORT", MENUSORT);
	}

	public java.lang.Double getMENUSORT() {
		return get("MENUSORT");
	}

	public void setISHIDE(java.lang.Integer ISHIDE) {
		set("ISHIDE", ISHIDE);
	}

	public java.lang.Integer getISHIDE() {
		return get("ISHIDE");
	}

	public void setDELFLAG(java.lang.Integer DELFLAG) {
		set("DELFLAG", DELFLAG);
	}

	public java.lang.Integer getDELFLAG() {
		return get("DELFLAG");
	}

}
