package org.manage.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("APPMENU", "MENUID", APPMENU.class);
		arp.addMapping("APPROLE", "ROLEID", APPROLE.class);
		// Composite Primary Key order: ROLEID,MENUID
		arp.addMapping("APPROLE_MENU", "ROLEID,MENUID", ApproleMenu.class);
		arp.addMapping("APPUSER", "USERID", APPUSER.class);
		// Composite Primary Key order: USERID,ROLEID
		arp.addMapping("APPUSER_ROLE", "USERID,ROLEID", AppuserRole.class);
		arp.addMapping("APPUSERINFO", "USERID", APPUSERINFO.class);
		arp.addMapping("APPUSERTYPE", "USERTYPEID", APPUSERTYPE.class);
		arp.addMapping("cost", "ID", Cost.class);
		arp.addMapping("customerinfo", "ID", Customerinfo.class);
		arp.addMapping("work", "ID", Work.class);
	}
}

