package org.manage.model;

import org.manage.model.base.BaseAPPMENU;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class APPMENU extends BaseAPPMENU<APPMENU> {
	public static final APPMENU dao = new APPMENU().dao();

	public List<APPMENU> getList(String parent, String menuid){
		String sql="";
		if (!"".equals(parent)&&parent!=null){
			sql="where PARENTID="+Integer.parseInt(parent);
		}else if (!"".equals(menuid)&&menuid!=null){
			sql="where MENUID="+Integer.parseInt(menuid);
		}else {
			sql="where PARENTID=0";
		}
		sql=sql+" and DELFLAG=0 order by MENUSORT,MENUID";
		List<APPMENU> appmenuList=APPMENU.dao.find("select * from APPMENU "+sql);
		return appmenuList;
	}

	public APPMENU getMenu(String menuid){
		String sql="select * from APPMENU where MENUID=?";
		APPMENU appmenu=APPMENU.dao.findFirst(sql,Integer.parseInt(menuid));
		return appmenu;
	}
	public List<APPMENU> getListTree(){
		String sql="select * from APPMENU where DELFLAG=0 order by MENUSORT,MENUID";
		List<APPMENU> appmenuList=APPMENU.dao.find(sql);
		return appmenuList;
	}
}
