package org.manage.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;
import org.manage.model.base.BaseApproleMenu;
import org.manage.util.Strings;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApproleMenu extends BaseApproleMenu<ApproleMenu> {
	public static final ApproleMenu dao = new ApproleMenu().dao();


	public List<ApproleMenu> getRoleList(String roleID){
		String sql="select MENUID from approle_menu where roleid=?";
		List<ApproleMenu> approleMenuList=ApproleMenu.dao.find(sql,Integer.parseInt(roleID));
		return approleMenuList;
	}

	public Map<String,Object> roleSave(String roleID, String menuIDs){
		Map<String,Object> retMap=new HashMap<String,Object>();
		Integer roleid=Integer.parseInt(roleID);
		List<String> sqlstring=new ArrayList<String>();
		for (String menuID:menuIDs.split(",")){
			if (!Strings.isNullOrEmpty(menuID)){
				sqlstring.add("insert into APPROLE_MENU (roleid,menuid) values ("+Integer.parseInt(roleID)+","+Integer.parseInt(menuID)+")");
			}
		}
		Db.tx(new IAtom() {
			@Override
			public boolean run() throws SQLException {
				Db.update("delete from APPROLE_MENU where ROLEID = ?", roleid);
				Db.batch(sqlstring,100);
				return true;
			}
		});
		retMap.put("code",1);
		return retMap;
	}
}
