package org.manage.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;
import org.manage.model.base.BaseAppuserRole;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppuserRole extends BaseAppuserRole<AppuserRole> {
	public static final AppuserRole dao = new AppuserRole().dao();
	public AppuserRole checkRole(String userid){
		AppuserRole role=AppuserRole.dao.findFirst("select * from APPUSER_ROLE where USERID=?",userid);
		return role;
	}
	public List<AppuserRole> getAppuserRoleList(String userid){
		String sql="select ROLEID from APPUSER_ROLE where USERID=?";
		List<AppuserRole> appuserRoleList=AppuserRole.dao.find(sql,userid);
		return appuserRoleList;
	}
	public Map<String,Object> updateRole(String roleList, String userID){
		Map<String,Object> retMap=new HashMap<String, Object>();
		String delStr="delete from APPUSER_ROLE where USERID=?";
		String insertStr="insert into APPUSER_ROLE(USERID,ROLEID) values (?,?)";
		String[] roles=roleList.split(",");
		Db.tx(new IAtom() {
			@Override
			public boolean run() throws SQLException {
				Db.update(delStr,userID);
				for (String role:roles){
					Db.update(insertStr,userID,Integer.parseInt(role));
				}
				return true;
			}
		});
		retMap.put("code",1);
		retMap.put("msg","");
		return retMap;
	}
}
