package org.manage.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import org.manage.model.base.BaseAPPUSERINFO;
import org.manage.util.Pager;
import org.manage.util.Pagination;
import org.manage.util.SqlBuilder;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class APPUSERINFO extends BaseAPPUSERINFO<APPUSERINFO> {
	public static final APPUSERINFO dao = new APPUSERINFO().dao();

	public Map<String,Object> getList(Map<String,String> paramMap,int uid){
		String sqlFrom=" from APPUSERINFO a,APPUSER b where a.USERID=b.MAPID and b.DELFLAG=0 and a.DELFLAG=0";
		SqlBuilder sqlBuilder = new SqlBuilder(null);
		sqlBuilder.addCondition("b","USERTYPEID", SqlBuilder.Condition.EQ,paramMap.get("TYPE"));
		sqlBuilder.addCondition("a","NAME", SqlBuilder.Condition.RLIKE,paramMap.get("NAME"));
		String sql = sqlBuilder.build();
		Object[] pars = sqlBuilder.paras();
		sqlFrom+=sql;
		Page<Record> page = Pagination.JPaginate(paramMap,"select a.*,b.USERID APPUSERID,b.USERSTATUS,b.LOGINNAME,"+uid+" as UID",sqlFrom+" order by b.USERSTATUS",pars);
		Map<String,Object> retMap = Pager.PageMap(paramMap,page);
		return retMap;
	}

	public Record getAppUserInfo1(String userID){
		String sql="select a.*,b.LOGINNAME from APPUSERINFO a,APPUSER b where a.USERID=b.MAPID AND a.USERID=?";
		Record record=Db.findFirst(sql,userID);
		return record;
	}
	public Map<String, Object> getList_e(Map<String,String> paramMap){
		StringBuffer sb = new StringBuffer();
		String sqlFrom="from appuser a,TBENTITY b where a.QYID=b.ENTITYID and a.DELFLAG=0 and a.USERTYPEID=6";
		SqlBuilder sqlBuilder = new SqlBuilder(null);
		sqlBuilder.addCondition("a","REALNAME", SqlBuilder.Condition.RLIKE,paramMap.get("CNAME"));
		String sql = sqlBuilder.build();
		sqlFrom+=sql;
		Object[] pars = sqlBuilder.paras();

		Page<Record> page = Pagination.JPaginate(paramMap,"select a.USERID,a.LOGINNAME,a.REALNAME,a.USERSTATUS,b.ENTITYNAME,b.ENTITYPARENTID,b.ENTITYDESCRIPTION",sqlFrom+" order by b.ENTITYID",pars);
		Map<String,Object> retMap = Pager.PageMap(paramMap,page);
		return retMap;
	}
}
