package org.manage.model;

import org.manage.model.base.BaseAPPUSERTYPE;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class APPUSERTYPE extends BaseAPPUSERTYPE<APPUSERTYPE> {
	public static final APPUSERTYPE dao = new APPUSERTYPE().dao();
	public List<APPUSERTYPE> getList(){
		List<APPUSERTYPE> appusertypeList=new ArrayList<APPUSERTYPE>();
		appusertypeList= APPUSERTYPE.dao.find("select USERTYPEID,USERTYPENAME from APPUSERTYPE");
		return appusertypeList;
	}
}
