package org.manage.model;

import com.jfinal.plugin.activerecord.Page;
import org.manage.model.base.BaseCost;
import org.manage.util.Pager;
import org.manage.util.Pagination;
import org.manage.util.SqlBuilder;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cost extends BaseCost<Cost> {
	public static final Cost dao = new Cost().dao();

	public Map<String,Object> getCostList(Map<String,String> params){
		String sqlFrom = "from cost where delflag=0";
		SqlBuilder sqlBuilder = new SqlBuilder(null);
		sqlBuilder.addCondition("costDetails", SqlBuilder.Condition.EQ,params.get("costDetails"));
		sqlBuilder.addCondition("date", SqlBuilder.Condition.GE,params.get("startDate"));
		sqlBuilder.addCondition("date", SqlBuilder.Condition.LE,params.get("endDate"));
		String sql = sqlBuilder.build();
		Object[] paras = sqlBuilder.paras();
		sqlFrom+=sql;
		Page<Work> workPage = Pagination.JPaginate(params,Work.dao,"select * ",sqlFrom,paras);
		Map<String,Object> retMap = Pager.PageMap(params,workPage);
		return retMap;
	}
	public Cost getCostInfo(String id){
		Cost cost = Cost.dao.findFirst("select * from cost where delflag = 0 and id=?",id);
		return cost;
	}
}
