package org.manage.model;

import org.manage.model.base.BasePayhist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Payhist extends BasePayhist<Payhist> {
	public static final Payhist dao = new Payhist().dao();
}
